// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6kHh4FdqTFuZJoPdIBdWk-6bPAjFmjk',
    appId: '1:894523733372:web:357a81dbad484da99d20f9',
    messagingSenderId: '894523733372',
    projectId: 'main-2ad03',
    authDomain: 'main-2ad03.firebaseapp.com',
    storageBucket: 'main-2ad03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxnJF5BMdScecl7ksaE6evVFHOlcZZIA',
    appId: '1:894523733372:android:3fd7c893a17fd0069d20f9',
    messagingSenderId: '894523733372',
    projectId: 'main-2ad03',
    storageBucket: 'main-2ad03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRConIF68SslIQ2YzCmcNdTd5P2t_Ans',
    appId: '1:894523733372:ios:657d06ef0f96e1a29d20f9',
    messagingSenderId: '894523733372',
    projectId: 'main-2ad03',
    storageBucket: 'main-2ad03.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkRConIF68SslIQ2YzCmcNdTd5P2t_Ans',
    appId: '1:894523733372:ios:657d06ef0f96e1a29d20f9',
    messagingSenderId: '894523733372',
    projectId: 'main-2ad03',
    storageBucket: 'main-2ad03.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6kHh4FdqTFuZJoPdIBdWk-6bPAjFmjk',
    appId: '1:894523733372:web:85d1c86e2eee5bc69d20f9',
    messagingSenderId: '894523733372',
    projectId: 'main-2ad03',
    authDomain: 'main-2ad03.firebaseapp.com',
    storageBucket: 'main-2ad03.firebasestorage.app',
  );
}
